name: "Main"

on:
  push:
    branches: [ "*" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
    #schedule:
    #- cron: '0 0 * * 5'

jobs:
  cancel-previous:
    name: Cancel previous runs
    runs-on: ubuntu-22.04

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{github.token}} # needs other token https://github.com/styfle/cancel-workflow-action/issues/7

  build-linux:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{matrix.language}}
        
    - name: Install deps
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends build-essential \
          cmake gcovr qtbase5-dev qtdeclarative5-dev qttools5-dev qttools5-dev-tools \
          valgrind python3 astyle qt6-l10n-tools \
          libgl1-mesa-dev libjemalloc-dev libjansson-dev libcurl4-openssl-dev
          
    - name: Make Release
      shell: bash
      run : |
        rm -rf build
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=RELEASE
        cmake --build . -j

  build-macos:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: Debug # tests only
            os: macos-latest
            xcode: 12.5.1
            qt_version: 6
            type: Debug
            do_tests: 0

          - target: 10.14_Mojave
            os: macos-10.15 # runs on Catalina
            xcode: 10.3 # allows compatibility with macOS 10.14
            qt_version: 5
            type: Release
            do_tests: 0
            make_package: 1

          - target: 10.15_Catalina
            os: macos-10.15
            xcode: 12.4
            qt_version: 6
            type: Release
            do_tests: 0
            make_package: 1

          - target: 11_Big_Sur
            os: macos-11
            xcode: 13.2
            qt_version: 6
            type: Release
            do_tests: 0
            make_package: 1

#          - target: 12_Monterey
#            os: macos-12
#            xcode: 13.3
#            qt_version: 6
#            type: Release
#            do_tests: 1
#            make_package: 1

    name: macOS ${{matrix.target}}
    runs-on: windows-2019
    env:
      CMAKE_GENERATOR: 'Visual Studio 16 2019'

    steps:          
      - name: Add msbuild to PATH
        id: add-msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly

      - name: Install Qt ${{matrix.qt_version}} for ${{matrix.target}}
        uses: jurplel/install-qt-action@v3
        with:
          cache: true
          version: ${{matrix.qt_version}}
          arch: win${{matrix.arch}}_${{matrix.qt_arch}}
          tools: ${{matrix.qt_tools}}
          modules: ${{matrix.qt_modules}}

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10.6
        with:
          runVcpkgInstall: true
          appendedCacheKey: ${{matrix.arch}}-bit
        env:
          VCPKG_DEFAULT_TRIPLET: '${{matrix.vcpkg_default_triplet}}-windows'
          VCPKG_DISABLE_METRICS: 1

      - name: Build Squire Desktop
        id: build
        shell: bash
        env:
          QTDIR: '${{github.workspace}}\Qt\${{matrix.qt_version}}\win${{matrix.arch}}_${{matrix.qt_arch}}'
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . -j
